[2024-11-07T18:04:02.515+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-11-07T18:04:01.221177+00:00 [queued]>
[2024-11-07T18:04:02.532+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-11-07T18:04:01.221177+00:00 [queued]>
[2024-11-07T18:04:02.533+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-07T18:04:02.533+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-07T18:04:02.533+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-07T18:04:02.559+0000] {taskinstance.py:1300} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2024-11-07 18:04:01.221177+00:00
[2024-11-07T18:04:02.567+0000] {standard_task_runner.py:55} INFO - Started process 1763 to run task
[2024-11-07T18:04:02.573+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_***_dag', 'spark_submit_task', 'manual__2024-11-07T18:04:01.221177+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/spark_jobs_dag.py', '--cfg-path', '/tmp/tmpfqthr_60']
[2024-11-07T18:04:02.574+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask spark_submit_task
[2024-11-07T18:04:02.598+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-11-07T18:04:02.702+0000] {task_command.py:388} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-11-07T18:04:01.221177+00:00 [running]> on host 25d0a0554898
[2024-11-07T18:04:02.829+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_***_dag
AIRFLOW_CTX_TASK_ID=spark_submit_task
AIRFLOW_CTX_EXECUTION_DATE=2024-11-07T18:04:01.221177+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-07T18:04:01.221177+00:00
[2024-11-07T18:04:02.844+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2024-11-07T18:04:02.847+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://localhost:7077 --name arrow-spark --queue root.default /opt/***/dags/spark_etl_script_docker.py
[2024-11-07T18:04:03.015+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-11-07T18:04:07.599+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:07 INFO SparkContext: Running Spark version 3.4.4
[2024-11-07T18:04:07.780+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:07 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-11-07T18:04:07.961+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:07 INFO ResourceUtils: ==============================================================
[2024-11-07T18:04:07.964+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:07 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-11-07T18:04:07.967+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:07 INFO ResourceUtils: ==============================================================
[2024-11-07T18:04:07.970+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:07 INFO SparkContext: Submitted application: DataExtraction
[2024-11-07T18:04:08.025+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-11-07T18:04:08.043+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO ResourceProfile: Limiting resource is cpu
[2024-11-07T18:04:08.044+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-11-07T18:04:08.118+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO SecurityManager: Changing view acls to: default
[2024-11-07T18:04:08.119+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO SecurityManager: Changing modify acls to: default
[2024-11-07T18:04:08.120+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO SecurityManager: Changing view acls groups to:
[2024-11-07T18:04:08.121+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO SecurityManager: Changing modify acls groups to:
[2024-11-07T18:04:08.122+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2024-11-07T18:04:08.587+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO Utils: Successfully started service 'sparkDriver' on port 45863.
[2024-11-07T18:04:08.625+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO SparkEnv: Registering MapOutputTracker
[2024-11-07T18:04:08.671+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO SparkEnv: Registering BlockManagerMaster
[2024-11-07T18:04:08.699+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-11-07T18:04:08.699+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-11-07T18:04:08.706+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-11-07T18:04:08.734+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-f5befb22-e1a5-44d1-89c7-7af5d2edd358
[2024-11-07T18:04:08.756+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-11-07T18:04:08.778+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:08 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-11-07T18:04:09.030+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:09 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-11-07T18:04:09.167+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:09 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-11-07T18:04:09.347+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:09 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://localhost:7077...
[2024-11-07T18:04:09.424+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:09 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master localhost:7077
[2024-11-07T18:04:09.425+0000] {spark_submit.py:490} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-07T18:04:09.425+0000] {spark_submit.py:490} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2024-11-07T18:04:09.425+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-07T18:04:09.426+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-07T18:04:09.426+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-07T18:04:09.426+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-07T18:04:09.427+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-11-07T18:04:09.427+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-07T18:04:09.428+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-11-07T18:04:09.428+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-11-07T18:04:09.429+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:04:09.429+0000] {spark_submit.py:490} INFO - Caused by: java.io.IOException: Failed to connect to localhost/127.0.0.1:7077
[2024-11-07T18:04:09.429+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-07T18:04:09.430+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-07T18:04:09.430+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-07T18:04:09.430+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-07T18:04:09.431+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-07T18:04:09.431+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-07T18:04:09.431+0000] {spark_submit.py:490} INFO - ... 4 more
[2024-11-07T18:04:09.432+0000] {spark_submit.py:490} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:7077
[2024-11-07T18:04:09.432+0000] {spark_submit.py:490} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-07T18:04:09.433+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-11-07T18:04:09.433+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-11-07T18:04:09.433+0000] {spark_submit.py:490} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-07T18:04:09.434+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-07T18:04:09.434+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-07T18:04:09.435+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-07T18:04:09.435+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-07T18:04:09.435+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-07T18:04:09.436+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-07T18:04:09.436+0000] {spark_submit.py:490} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-07T18:04:09.437+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-07T18:04:09.437+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:04:29.343+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:29 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://localhost:7077...
[2024-11-07T18:04:29.355+0000] {spark_submit.py:490} INFO - 24/11/07 18:04:29 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master localhost:7077
[2024-11-07T18:04:29.356+0000] {spark_submit.py:490} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-07T18:04:29.356+0000] {spark_submit.py:490} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2024-11-07T18:04:29.357+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-07T18:04:29.357+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-07T18:04:29.357+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-07T18:04:29.358+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-07T18:04:29.358+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-11-07T18:04:29.358+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-07T18:04:29.359+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-11-07T18:04:29.359+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-11-07T18:04:29.359+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:04:29.360+0000] {spark_submit.py:490} INFO - Caused by: java.io.IOException: Failed to connect to localhost/127.0.0.1:7077
[2024-11-07T18:04:29.360+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-07T18:04:29.360+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-07T18:04:29.361+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-07T18:04:29.361+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-07T18:04:29.361+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-07T18:04:29.362+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-07T18:04:29.362+0000] {spark_submit.py:490} INFO - ... 4 more
[2024-11-07T18:04:29.362+0000] {spark_submit.py:490} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:7077
[2024-11-07T18:04:29.363+0000] {spark_submit.py:490} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-07T18:04:29.363+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-11-07T18:04:29.363+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-11-07T18:04:29.363+0000] {spark_submit.py:490} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-07T18:04:29.364+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-07T18:04:29.364+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-07T18:04:29.364+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-07T18:04:29.365+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-07T18:04:29.365+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-07T18:04:29.366+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-07T18:04:29.366+0000] {spark_submit.py:490} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-07T18:04:29.366+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-07T18:04:29.367+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:04:43.041+0000] {local_task_job.py:273} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-11-07T18:04:43.050+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1763. PIDs of all processes in the group: [1764, 1826, 1763]
[2024-11-07T18:04:43.052+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1763
[2024-11-07T18:04:43.052+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-07T18:04:43.054+0000] {spark_submit.py:615} INFO - Sending kill signal to spark-submit
[2024-11-07T18:04:43.116+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1764, status='terminated', started='18:04:02') (1764) terminated with exit code None
[2024-11-07T18:04:43.121+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1763, status='terminated', exitcode=0, started='18:04:02') (1763) terminated with exit code 0
[2024-11-07T18:04:43.122+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1826, status='terminated', started='18:04:06') (1826) terminated with exit code None
