[2024-11-08T05:52:11.539+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-11-08T05:52:08.753664+00:00 [queued]>
[2024-11-08T05:52:11.593+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-11-08T05:52:08.753664+00:00 [queued]>
[2024-11-08T05:52:11.596+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-08T05:52:11.597+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-08T05:52:11.604+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-08T05:52:11.717+0000] {taskinstance.py:1300} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2024-11-08 05:52:08.753664+00:00
[2024-11-08T05:52:11.732+0000] {standard_task_runner.py:55} INFO - Started process 1018 to run task
[2024-11-08T05:52:11.740+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_***_dag', 'spark_submit_task', 'manual__2024-11-08T05:52:08.753664+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/spark_jobs_dag.py', '--cfg-path', '/tmp/tmpxq7x6as9']
[2024-11-08T05:52:11.741+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask spark_submit_task
[2024-11-08T05:52:11.766+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-11-08T05:52:11.871+0000] {task_command.py:388} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-11-08T05:52:08.753664+00:00 [running]> on host 9b102d56f177
[2024-11-08T05:52:12.021+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_***_dag
AIRFLOW_CTX_TASK_ID=spark_submit_task
AIRFLOW_CTX_EXECUTION_DATE=2024-11-08T05:52:08.753664+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-08T05:52:08.753664+00:00
[2024-11-08T05:52:12.039+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2024-11-08T05:52:12.043+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://85981e16de87:7077 --name arrow-spark --queue root.default /opt/***/dags/spark_etl_script_docker.py
[2024-11-08T05:52:12.380+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-11-08T05:52:22.203+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO SparkContext: Running Spark version 3.4.4
[2024-11-08T05:52:22.415+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-11-08T05:52:22.669+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO ResourceUtils: ==============================================================
[2024-11-08T05:52:22.670+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-11-08T05:52:22.671+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO ResourceUtils: ==============================================================
[2024-11-08T05:52:22.673+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO SparkContext: Submitted application: MutualFundDataExtraction
[2024-11-08T05:52:22.744+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-11-08T05:52:22.782+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO ResourceProfile: Limiting resource is cpu
[2024-11-08T05:52:22.783+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-11-08T05:52:22.949+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO SecurityManager: Changing view acls to: default
[2024-11-08T05:52:22.949+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO SecurityManager: Changing modify acls to: default
[2024-11-08T05:52:22.951+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO SecurityManager: Changing view acls groups to:
[2024-11-08T05:52:22.952+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO SecurityManager: Changing modify acls groups to:
[2024-11-08T05:52:22.953+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:22 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2024-11-08T05:52:24.316+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:24 INFO Utils: Successfully started service 'sparkDriver' on port 33177.
[2024-11-08T05:52:24.382+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:24 INFO SparkEnv: Registering MapOutputTracker
[2024-11-08T05:52:24.462+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:24 INFO SparkEnv: Registering BlockManagerMaster
[2024-11-08T05:52:24.512+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:24 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-11-08T05:52:24.514+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:24 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-11-08T05:52:24.523+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:24 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-11-08T05:52:24.587+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:24 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-9d0b96d2-5b32-40a5-aebe-1ef273af918e
[2024-11-08T05:52:24.641+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:24 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-11-08T05:52:24.699+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:24 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-11-08T05:52:25.105+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:25 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-11-08T05:52:25.315+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:25 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-11-08T05:52:25.682+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:25 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://85981e16de87:7077...
[2024-11-08T05:52:25.892+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:25 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 85981e16de87:7077
[2024-11-08T05:52:25.893+0000] {spark_submit.py:490} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-08T05:52:25.893+0000] {spark_submit.py:490} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2024-11-08T05:52:25.894+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-08T05:52:25.895+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-08T05:52:25.896+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-08T05:52:25.896+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-08T05:52:25.897+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-11-08T05:52:25.897+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-08T05:52:25.898+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-11-08T05:52:25.899+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-11-08T05:52:25.900+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:52:25.900+0000] {spark_submit.py:490} INFO - Caused by: java.io.IOException: Failed to connect to 85981e16de87/172.18.0.2:7077
[2024-11-08T05:52:25.901+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-08T05:52:25.902+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-08T05:52:25.902+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-08T05:52:25.903+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-08T05:52:25.904+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-08T05:52:25.904+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-08T05:52:25.905+0000] {spark_submit.py:490} INFO - ... 4 more
[2024-11-08T05:52:25.906+0000] {spark_submit.py:490} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 85981e16de87/172.18.0.2:7077
[2024-11-08T05:52:25.906+0000] {spark_submit.py:490} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-08T05:52:25.907+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-11-08T05:52:25.907+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-11-08T05:52:25.908+0000] {spark_submit.py:490} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-08T05:52:25.909+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-08T05:52:25.909+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-08T05:52:25.910+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-08T05:52:25.910+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-08T05:52:25.911+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-08T05:52:25.912+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-08T05:52:25.913+0000] {spark_submit.py:490} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-08T05:52:25.913+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-08T05:52:25.914+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:52:45.691+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:45 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://85981e16de87:7077...
[2024-11-08T05:52:45.705+0000] {spark_submit.py:490} INFO - 24/11/08 05:52:45 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 85981e16de87:7077
[2024-11-08T05:52:45.705+0000] {spark_submit.py:490} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-08T05:52:45.706+0000] {spark_submit.py:490} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2024-11-08T05:52:45.706+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-08T05:52:45.707+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-08T05:52:45.707+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-08T05:52:45.708+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-08T05:52:45.708+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-11-08T05:52:45.709+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-08T05:52:45.709+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-11-08T05:52:45.709+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-11-08T05:52:45.710+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:52:45.710+0000] {spark_submit.py:490} INFO - Caused by: java.io.IOException: Failed to connect to 85981e16de87/172.18.0.2:7077
[2024-11-08T05:52:45.711+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-08T05:52:45.711+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-08T05:52:45.712+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-08T05:52:45.712+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-08T05:52:45.712+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-08T05:52:45.713+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-08T05:52:45.713+0000] {spark_submit.py:490} INFO - ... 4 more
[2024-11-08T05:52:45.714+0000] {spark_submit.py:490} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 85981e16de87/172.18.0.2:7077
[2024-11-08T05:52:45.714+0000] {spark_submit.py:490} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-08T05:52:45.714+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-11-08T05:52:45.715+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-11-08T05:52:45.715+0000] {spark_submit.py:490} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-08T05:52:45.715+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-08T05:52:45.716+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-08T05:52:45.716+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-08T05:52:45.717+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-08T05:52:45.717+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-08T05:52:45.718+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-08T05:52:45.718+0000] {spark_submit.py:490} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-08T05:52:45.718+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-08T05:52:45.719+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:53:05.696+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:05 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://85981e16de87:7077...
[2024-11-08T05:53:05.713+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:05 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 85981e16de87:7077
[2024-11-08T05:53:05.714+0000] {spark_submit.py:490} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-08T05:53:05.717+0000] {spark_submit.py:490} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2024-11-08T05:53:05.717+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-08T05:53:05.718+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-08T05:53:05.721+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-08T05:53:05.721+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-08T05:53:05.722+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-11-08T05:53:05.723+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-08T05:53:05.723+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-11-08T05:53:05.724+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-11-08T05:53:05.724+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:53:05.725+0000] {spark_submit.py:490} INFO - Caused by: java.io.IOException: Failed to connect to 85981e16de87/172.18.0.2:7077
[2024-11-08T05:53:05.725+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-08T05:53:05.726+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-08T05:53:05.726+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-08T05:53:05.727+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-08T05:53:05.728+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-08T05:53:05.728+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-08T05:53:05.728+0000] {spark_submit.py:490} INFO - ... 4 more
[2024-11-08T05:53:05.729+0000] {spark_submit.py:490} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 85981e16de87/172.18.0.2:7077
[2024-11-08T05:53:05.729+0000] {spark_submit.py:490} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-08T05:53:05.730+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-11-08T05:53:05.731+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-11-08T05:53:05.731+0000] {spark_submit.py:490} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-08T05:53:05.732+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-08T05:53:05.733+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-08T05:53:05.734+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-08T05:53:05.736+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-08T05:53:05.736+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-08T05:53:05.737+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-08T05:53:05.737+0000] {spark_submit.py:490} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-08T05:53:05.738+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-08T05:53:05.739+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:53:25.698+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:25 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2024-11-08T05:53:25.701+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:25 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2024-11-08T05:53:25.737+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:25 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45303.
[2024-11-08T05:53:25.741+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:25 INFO NettyBlockTransferService: Server created on 9b102d56f177:45303
[2024-11-08T05:53:25.742+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:25 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-11-08T05:53:25.760+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:25 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 9b102d56f177, 45303, None)
[2024-11-08T05:53:25.769+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:25 INFO BlockManagerMasterEndpoint: Registering block manager 9b102d56f177:45303 with 434.4 MiB RAM, BlockManagerId(driver, 9b102d56f177, 45303, None)
[2024-11-08T05:53:25.776+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:25 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 9b102d56f177, 45303, None)
[2024-11-08T05:53:25.780+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:25 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 9b102d56f177, 45303, None)
[2024-11-08T05:53:26.368+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:26 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-11-08T05:53:26.463+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py:317: FutureWarning: Python 3.7 support is deprecated in Spark 3.4.
[2024-11-08T05:53:26.465+0000] {spark_submit.py:490} INFO - warnings.warn("Python 3.7 support is deprecated in Spark 3.4.", FutureWarning)
[2024-11-08T05:53:26.796+0000] {spark_submit.py:490} INFO - INFO:__main__:SparkSession created successfully
[2024-11-08T05:53:26.966+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:26 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-11-08T05:53:26.990+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:26 INFO SparkUI: Stopped Spark web UI at http://9b102d56f177:4040
[2024-11-08T05:53:27.004+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-11-08T05:53:27.010+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-11-08T05:53:27.019+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2024-11-08T05:53:27.045+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-11-08T05:53:27.085+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO MemoryStore: MemoryStore cleared
[2024-11-08T05:53:27.085+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO BlockManager: BlockManager stopped
[2024-11-08T05:53:27.095+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-11-08T05:53:27.099+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-11-08T05:53:27.189+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO SparkContext: Successfully stopped SparkContext
[2024-11-08T05:53:27.309+0000] {spark_submit.py:490} INFO - INFO:__main__:Successfully fetched mutual fund data
[2024-11-08T05:53:27.388+0000] {spark_submit.py:490} INFO - ERROR:__main__:Error processing mutual fund data: An error occurred while calling o24.defaultParallelism.
[2024-11-08T05:53:27.388+0000] {spark_submit.py:490} INFO - : java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
[2024-11-08T05:53:27.389+0000] {spark_submit.py:490} INFO - This stopped SparkContext was created at:
[2024-11-08T05:53:27.389+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.390+0000] {spark_submit.py:490} INFO - org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-11-08T05:53:27.390+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-11-08T05:53:27.391+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2024-11-08T05:53:27.391+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-11-08T05:53:27.395+0000] {spark_submit.py:490} INFO - java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2024-11-08T05:53:27.395+0000] {spark_submit.py:490} INFO - py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-11-08T05:53:27.396+0000] {spark_submit.py:490} INFO - py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-08T05:53:27.396+0000] {spark_submit.py:490} INFO - py4j.Gateway.invoke(Gateway.java:238)
[2024-11-08T05:53:27.396+0000] {spark_submit.py:490} INFO - py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-11-08T05:53:27.397+0000] {spark_submit.py:490} INFO - py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-11-08T05:53:27.397+0000] {spark_submit.py:490} INFO - py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-08T05:53:27.398+0000] {spark_submit.py:490} INFO - py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-08T05:53:27.398+0000] {spark_submit.py:490} INFO - java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:53:27.400+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.400+0000] {spark_submit.py:490} INFO - The currently active SparkContext was created at:
[2024-11-08T05:53:27.400+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.401+0000] {spark_submit.py:490} INFO - (No active SparkContext.)
[2024-11-08T05:53:27.402+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.403+0000] {spark_submit.py:490} INFO - at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:120)
[2024-11-08T05:53:27.403+0000] {spark_submit.py:490} INFO - at org.apache.spark.SparkContext.defaultParallelism(SparkContext.scala:2554)
[2024-11-08T05:53:27.407+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-11-08T05:53:27.407+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-11-08T05:53:27.408+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-11-08T05:53:27.409+0000] {spark_submit.py:490} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-11-08T05:53:27.409+0000] {spark_submit.py:490} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-11-08T05:53:27.409+0000] {spark_submit.py:490} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-08T05:53:27.410+0000] {spark_submit.py:490} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-11-08T05:53:27.410+0000] {spark_submit.py:490} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-11-08T05:53:27.411+0000] {spark_submit.py:490} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-11-08T05:53:27.412+0000] {spark_submit.py:490} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-08T05:53:27.412+0000] {spark_submit.py:490} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-08T05:53:27.413+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:53:27.413+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.414+0000] {spark_submit.py:490} INFO - ERROR:__main__:Main process failed: An error occurred while calling o24.defaultParallelism.
[2024-11-08T05:53:27.415+0000] {spark_submit.py:490} INFO - : java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
[2024-11-08T05:53:27.417+0000] {spark_submit.py:490} INFO - This stopped SparkContext was created at:
[2024-11-08T05:53:27.418+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.418+0000] {spark_submit.py:490} INFO - org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-11-08T05:53:27.419+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-11-08T05:53:27.420+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2024-11-08T05:53:27.420+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-11-08T05:53:27.421+0000] {spark_submit.py:490} INFO - java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2024-11-08T05:53:27.421+0000] {spark_submit.py:490} INFO - py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-11-08T05:53:27.423+0000] {spark_submit.py:490} INFO - py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-08T05:53:27.425+0000] {spark_submit.py:490} INFO - py4j.Gateway.invoke(Gateway.java:238)
[2024-11-08T05:53:27.427+0000] {spark_submit.py:490} INFO - py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-11-08T05:53:27.427+0000] {spark_submit.py:490} INFO - py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-11-08T05:53:27.428+0000] {spark_submit.py:490} INFO - py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-08T05:53:27.428+0000] {spark_submit.py:490} INFO - py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-08T05:53:27.429+0000] {spark_submit.py:490} INFO - java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:53:27.430+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.431+0000] {spark_submit.py:490} INFO - The currently active SparkContext was created at:
[2024-11-08T05:53:27.432+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.432+0000] {spark_submit.py:490} INFO - (No active SparkContext.)
[2024-11-08T05:53:27.434+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.434+0000] {spark_submit.py:490} INFO - at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:120)
[2024-11-08T05:53:27.435+0000] {spark_submit.py:490} INFO - at org.apache.spark.SparkContext.defaultParallelism(SparkContext.scala:2554)
[2024-11-08T05:53:27.436+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-11-08T05:53:27.436+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-11-08T05:53:27.437+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-11-08T05:53:27.437+0000] {spark_submit.py:490} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-11-08T05:53:27.438+0000] {spark_submit.py:490} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-11-08T05:53:27.439+0000] {spark_submit.py:490} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-08T05:53:27.439+0000] {spark_submit.py:490} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-11-08T05:53:27.440+0000] {spark_submit.py:490} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-11-08T05:53:27.440+0000] {spark_submit.py:490} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-11-08T05:53:27.441+0000] {spark_submit.py:490} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-08T05:53:27.442+0000] {spark_submit.py:490} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-08T05:53:27.443+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:53:27.443+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.444+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-11-08T05:53:27.445+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO SparkContext: SparkContext already stopped.
[2024-11-08T05:53:27.446+0000] {spark_submit.py:490} INFO - INFO:__main__:SparkSession stopped successfully
[2024-11-08T05:53:27.446+0000] {spark_submit.py:490} INFO - Traceback (most recent call last):
[2024-11-08T05:53:27.447+0000] {spark_submit.py:490} INFO - File "/opt/***/dags/spark_etl_script_docker.py", line 121, in <module>
[2024-11-08T05:53:27.448+0000] {spark_submit.py:490} INFO - main()
[2024-11-08T05:53:27.449+0000] {spark_submit.py:490} INFO - File "/opt/***/dags/spark_etl_script_docker.py", line 97, in main
[2024-11-08T05:53:27.449+0000] {spark_submit.py:490} INFO - processed_df = process_mutual_fund_data(spark, raw_data)
[2024-11-08T05:53:27.451+0000] {spark_submit.py:490} INFO - File "/opt/***/dags/spark_etl_script_docker.py", line 50, in process_mutual_fund_data
[2024-11-08T05:53:27.452+0000] {spark_submit.py:490} INFO - rdd = spark.sparkContext.parallelize([data])
[2024-11-08T05:53:27.452+0000] {spark_submit.py:490} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 780, in parallelize
[2024-11-08T05:53:27.453+0000] {spark_submit.py:490} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 627, in defaultParallelism
[2024-11-08T05:53:27.454+0000] {spark_submit.py:490} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1323, in __call__
[2024-11-08T05:53:27.454+0000] {spark_submit.py:490} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 169, in deco
[2024-11-08T05:53:27.456+0000] {spark_submit.py:490} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 328, in get_return_value
[2024-11-08T05:53:27.457+0000] {spark_submit.py:490} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o24.defaultParallelism.
[2024-11-08T05:53:27.458+0000] {spark_submit.py:490} INFO - : java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
[2024-11-08T05:53:27.459+0000] {spark_submit.py:490} INFO - This stopped SparkContext was created at:
[2024-11-08T05:53:27.459+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.460+0000] {spark_submit.py:490} INFO - org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-11-08T05:53:27.460+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-11-08T05:53:27.461+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2024-11-08T05:53:27.461+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-11-08T05:53:27.462+0000] {spark_submit.py:490} INFO - java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2024-11-08T05:53:27.463+0000] {spark_submit.py:490} INFO - py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-11-08T05:53:27.463+0000] {spark_submit.py:490} INFO - py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-08T05:53:27.464+0000] {spark_submit.py:490} INFO - py4j.Gateway.invoke(Gateway.java:238)
[2024-11-08T05:53:27.465+0000] {spark_submit.py:490} INFO - py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-11-08T05:53:27.466+0000] {spark_submit.py:490} INFO - py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-11-08T05:53:27.466+0000] {spark_submit.py:490} INFO - py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-08T05:53:27.467+0000] {spark_submit.py:490} INFO - py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-08T05:53:27.468+0000] {spark_submit.py:490} INFO - java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:53:27.468+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.469+0000] {spark_submit.py:490} INFO - The currently active SparkContext was created at:
[2024-11-08T05:53:27.469+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.470+0000] {spark_submit.py:490} INFO - (No active SparkContext.)
[2024-11-08T05:53:27.470+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.471+0000] {spark_submit.py:490} INFO - at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:120)
[2024-11-08T05:53:27.472+0000] {spark_submit.py:490} INFO - at org.apache.spark.SparkContext.defaultParallelism(SparkContext.scala:2554)
[2024-11-08T05:53:27.473+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-11-08T05:53:27.474+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-11-08T05:53:27.474+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-11-08T05:53:27.475+0000] {spark_submit.py:490} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-11-08T05:53:27.476+0000] {spark_submit.py:490} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-11-08T05:53:27.476+0000] {spark_submit.py:490} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-08T05:53:27.477+0000] {spark_submit.py:490} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-11-08T05:53:27.478+0000] {spark_submit.py:490} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-11-08T05:53:27.479+0000] {spark_submit.py:490} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-11-08T05:53:27.480+0000] {spark_submit.py:490} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-08T05:53:27.482+0000] {spark_submit.py:490} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-08T05:53:27.483+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-08T05:53:27.483+0000] {spark_submit.py:490} INFO - 
[2024-11-08T05:53:27.583+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO ShutdownHookManager: Shutdown hook called
[2024-11-08T05:53:27.585+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-c310c671-24a3-4c6f-a955-e92bab3d5b2c/pyspark-19f2ca78-6141-4392-b776-fe25498d1e74
[2024-11-08T05:53:27.605+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-c310c671-24a3-4c6f-a955-e92bab3d5b2c
[2024-11-08T05:53:27.631+0000] {spark_submit.py:490} INFO - 24/11/08 05:53:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-ef7de1e2-9e3d-4dfd-9da8-870813ff1fc8
[2024-11-08T05:53:27.792+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://85981e16de87:7077 --name arrow-spark --queue root.default /opt/***/dags/spark_etl_script_docker.py. Error code is: 1.
[2024-11-08T05:53:27.814+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=spark_***_dag, task_id=spark_submit_task, execution_date=20241108T055208, start_date=20241108T055211, end_date=20241108T055327
[2024-11-08T05:53:27.862+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task spark_submit_task (Cannot execute: spark-submit --master spark://85981e16de87:7077 --name arrow-spark --queue root.default /opt/***/dags/spark_etl_script_docker.py. Error code is: 1.; 1018)
[2024-11-08T05:53:27.901+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-08T05:53:27.956+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
