[2024-11-07T18:02:07.306+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-11-07T18:02:05.412800+00:00 [queued]>
[2024-11-07T18:02:07.330+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-11-07T18:02:05.412800+00:00 [queued]>
[2024-11-07T18:02:07.331+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-07T18:02:07.331+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-07T18:02:07.332+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-07T18:02:07.364+0000] {taskinstance.py:1300} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2024-11-07 18:02:05.412800+00:00
[2024-11-07T18:02:07.373+0000] {standard_task_runner.py:55} INFO - Started process 1434 to run task
[2024-11-07T18:02:07.380+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_***_dag', 'spark_submit_task', 'manual__2024-11-07T18:02:05.412800+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/spark_jobs_dag.py', '--cfg-path', '/tmp/tmpwqmd6a0h']
[2024-11-07T18:02:07.381+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask spark_submit_task
[2024-11-07T18:02:07.410+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-11-07T18:02:07.518+0000] {task_command.py:388} INFO - Running <TaskInstance: spark_airflow_dag.spark_submit_task manual__2024-11-07T18:02:05.412800+00:00 [running]> on host 25d0a0554898
[2024-11-07T18:02:07.660+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_***_dag
AIRFLOW_CTX_TASK_ID=spark_submit_task
AIRFLOW_CTX_EXECUTION_DATE=2024-11-07T18:02:05.412800+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-07T18:02:05.412800+00:00
[2024-11-07T18:02:07.683+0000] {base.py:73} INFO - Using connection ID 'spark_local' for task execution.
[2024-11-07T18:02:07.687+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://172.19.0.2:7077 --name arrow-spark --queue root.default /opt/***/dags/spark_etl_script_docker.py
[2024-11-07T18:02:08.035+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-11-07T18:02:17.026+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO SparkContext: Running Spark version 3.4.4
[2024-11-07T18:02:17.179+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-11-07T18:02:17.397+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO ResourceUtils: ==============================================================
[2024-11-07T18:02:17.398+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-11-07T18:02:17.399+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO ResourceUtils: ==============================================================
[2024-11-07T18:02:17.400+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO SparkContext: Submitted application: DataExtraction
[2024-11-07T18:02:17.454+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-11-07T18:02:17.479+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO ResourceProfile: Limiting resource is cpu
[2024-11-07T18:02:17.480+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-11-07T18:02:17.583+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO SecurityManager: Changing view acls to: default
[2024-11-07T18:02:17.585+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO SecurityManager: Changing modify acls to: default
[2024-11-07T18:02:17.586+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO SecurityManager: Changing view acls groups to:
[2024-11-07T18:02:17.590+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO SecurityManager: Changing modify acls groups to:
[2024-11-07T18:02:17.591+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:17 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2024-11-07T18:02:18.419+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:18 INFO Utils: Successfully started service 'sparkDriver' on port 36679.
[2024-11-07T18:02:18.531+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:18 INFO SparkEnv: Registering MapOutputTracker
[2024-11-07T18:02:18.604+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:18 INFO SparkEnv: Registering BlockManagerMaster
[2024-11-07T18:02:18.642+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:18 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-11-07T18:02:18.644+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:18 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-11-07T18:02:18.650+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:18 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-11-07T18:02:18.696+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:18 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-1fbfbf2c-7e48-41e6-a9a5-316099ca1c16
[2024-11-07T18:02:18.770+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:18 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-11-07T18:02:18.828+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:18 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-11-07T18:02:19.191+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:19 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-11-07T18:02:19.396+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:19 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-11-07T18:02:19.703+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:19 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.19.0.2:7077...
[2024-11-07T18:02:19.804+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:19 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 172.19.0.2:7077
[2024-11-07T18:02:19.804+0000] {spark_submit.py:490} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-07T18:02:19.805+0000] {spark_submit.py:490} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2024-11-07T18:02:19.806+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-07T18:02:19.806+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-07T18:02:19.807+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-07T18:02:19.808+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-07T18:02:19.808+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-11-07T18:02:19.809+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-07T18:02:19.809+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-11-07T18:02:19.811+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-11-07T18:02:19.811+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:02:19.812+0000] {spark_submit.py:490} INFO - Caused by: java.io.IOException: Failed to connect to /172.19.0.2:7077
[2024-11-07T18:02:19.812+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-07T18:02:19.813+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-07T18:02:19.814+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-07T18:02:19.814+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-07T18:02:19.815+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-07T18:02:19.816+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-07T18:02:19.816+0000] {spark_submit.py:490} INFO - ... 4 more
[2024-11-07T18:02:19.817+0000] {spark_submit.py:490} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.19.0.2:7077
[2024-11-07T18:02:19.818+0000] {spark_submit.py:490} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-07T18:02:19.818+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-11-07T18:02:19.819+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-11-07T18:02:19.819+0000] {spark_submit.py:490} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-07T18:02:19.820+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-07T18:02:19.821+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-07T18:02:19.822+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-07T18:02:19.823+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-07T18:02:19.823+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-07T18:02:19.824+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-07T18:02:19.825+0000] {spark_submit.py:490} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-07T18:02:19.826+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-07T18:02:19.826+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:02:39.703+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:39 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.19.0.2:7077...
[2024-11-07T18:02:39.722+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:39 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 172.19.0.2:7077
[2024-11-07T18:02:39.723+0000] {spark_submit.py:490} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-07T18:02:39.723+0000] {spark_submit.py:490} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2024-11-07T18:02:39.724+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-07T18:02:39.724+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-07T18:02:39.725+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-07T18:02:39.726+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-07T18:02:39.727+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-11-07T18:02:39.728+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-07T18:02:39.729+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-11-07T18:02:39.730+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-11-07T18:02:39.731+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:02:39.731+0000] {spark_submit.py:490} INFO - Caused by: java.io.IOException: Failed to connect to /172.19.0.2:7077
[2024-11-07T18:02:39.732+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-07T18:02:39.732+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-07T18:02:39.733+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-07T18:02:39.733+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-07T18:02:39.734+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-07T18:02:39.734+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-07T18:02:39.735+0000] {spark_submit.py:490} INFO - ... 4 more
[2024-11-07T18:02:39.735+0000] {spark_submit.py:490} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.19.0.2:7077
[2024-11-07T18:02:39.736+0000] {spark_submit.py:490} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-07T18:02:39.736+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-11-07T18:02:39.737+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-11-07T18:02:39.737+0000] {spark_submit.py:490} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-07T18:02:39.737+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-07T18:02:39.738+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-07T18:02:39.739+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-07T18:02:39.739+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-07T18:02:39.739+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-07T18:02:39.740+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-07T18:02:39.740+0000] {spark_submit.py:490} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-07T18:02:39.741+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-07T18:02:39.742+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:02:59.724+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:59 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.19.0.2:7077...
[2024-11-07T18:02:59.785+0000] {spark_submit.py:490} INFO - 24/11/07 18:02:59 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master 172.19.0.2:7077
[2024-11-07T18:02:59.786+0000] {spark_submit.py:490} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-07T18:02:59.787+0000] {spark_submit.py:490} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:322)
[2024-11-07T18:02:59.788+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-07T18:02:59.789+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-07T18:02:59.790+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-07T18:02:59.791+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-07T18:02:59.792+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-11-07T18:02:59.793+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-07T18:02:59.794+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-11-07T18:02:59.798+0000] {spark_submit.py:490} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-11-07T18:02:59.800+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:02:59.801+0000] {spark_submit.py:490} INFO - Caused by: java.io.IOException: Failed to connect to /172.19.0.2:7077
[2024-11-07T18:02:59.802+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-07T18:02:59.802+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-07T18:02:59.803+0000] {spark_submit.py:490} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-07T18:02:59.804+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-07T18:02:59.804+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-07T18:02:59.805+0000] {spark_submit.py:490} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-07T18:02:59.805+0000] {spark_submit.py:490} INFO - ... 4 more
[2024-11-07T18:02:59.806+0000] {spark_submit.py:490} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.19.0.2:7077
[2024-11-07T18:02:59.807+0000] {spark_submit.py:490} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-07T18:02:59.810+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2024-11-07T18:02:59.812+0000] {spark_submit.py:490} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
[2024-11-07T18:02:59.814+0000] {spark_submit.py:490} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-07T18:02:59.819+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-07T18:02:59.825+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-07T18:02:59.828+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-07T18:02:59.833+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-07T18:02:59.836+0000] {spark_submit.py:490} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-07T18:02:59.840+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-07T18:02:59.846+0000] {spark_submit.py:490} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-07T18:02:59.847+0000] {spark_submit.py:490} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-07T18:02:59.849+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:03:19.738+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:19 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2024-11-07T18:03:19.739+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:19 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2024-11-07T18:03:19.782+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:19 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42665.
[2024-11-07T18:03:19.782+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:19 INFO NettyBlockTransferService: Server created on 25d0a0554898:42665
[2024-11-07T18:03:19.790+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:19 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-11-07T18:03:19.810+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:19 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 25d0a0554898, 42665, None)
[2024-11-07T18:03:19.820+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:19 INFO BlockManagerMasterEndpoint: Registering block manager 25d0a0554898:42665 with 434.4 MiB RAM, BlockManagerId(driver, 25d0a0554898, 42665, None)
[2024-11-07T18:03:19.826+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:19 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 25d0a0554898, 42665, None)
[2024-11-07T18:03:19.828+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:19 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 25d0a0554898, 42665, None)
[2024-11-07T18:03:20.511+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:20 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-11-07T18:03:20.601+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py:317: FutureWarning: Python 3.7 support is deprecated in Spark 3.4.
[2024-11-07T18:03:20.602+0000] {spark_submit.py:490} INFO - warnings.warn("Python 3.7 support is deprecated in Spark 3.4.", FutureWarning)
[2024-11-07T18:03:21.283+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:21 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-11-07T18:03:21.320+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:21 INFO SparkUI: Stopped Spark web UI at http://25d0a0554898:4040
[2024-11-07T18:03:21.357+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:21 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-11-07T18:03:21.369+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:21 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-11-07T18:03:21.381+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:21 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2024-11-07T18:03:21.428+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:21 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-11-07T18:03:21.491+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:21 INFO MemoryStore: MemoryStore cleared
[2024-11-07T18:03:21.493+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:21 INFO BlockManager: BlockManager stopped
[2024-11-07T18:03:21.506+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:21 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-11-07T18:03:21.512+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:21 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-11-07T18:03:21.550+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:21 INFO SparkContext: Successfully stopped SparkContext
[2024-11-07T18:03:21.869+0000] {spark_submit.py:490} INFO - Traceback (most recent call last):
[2024-11-07T18:03:21.873+0000] {spark_submit.py:490} INFO - File "/opt/***/dags/spark_etl_script_docker.py", line 25, in <module>
[2024-11-07T18:03:21.874+0000] {spark_submit.py:490} INFO - RDD = sparkContext.parallelize([data])
[2024-11-07T18:03:21.877+0000] {spark_submit.py:490} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 780, in parallelize
[2024-11-07T18:03:21.878+0000] {spark_submit.py:490} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 627, in defaultParallelism
[2024-11-07T18:03:21.879+0000] {spark_submit.py:490} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1323, in __call__
[2024-11-07T18:03:21.882+0000] {spark_submit.py:490} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 169, in deco
[2024-11-07T18:03:21.883+0000] {spark_submit.py:490} INFO - File "/home/***/.local/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 328, in get_return_value
[2024-11-07T18:03:21.884+0000] {spark_submit.py:490} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o24.defaultParallelism.
[2024-11-07T18:03:21.885+0000] {spark_submit.py:490} INFO - : java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
[2024-11-07T18:03:21.886+0000] {spark_submit.py:490} INFO - This stopped SparkContext was created at:
[2024-11-07T18:03:21.887+0000] {spark_submit.py:490} INFO - 
[2024-11-07T18:03:21.888+0000] {spark_submit.py:490} INFO - org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-11-07T18:03:21.889+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-11-07T18:03:21.889+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2024-11-07T18:03:21.890+0000] {spark_submit.py:490} INFO - java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-11-07T18:03:21.890+0000] {spark_submit.py:490} INFO - java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2024-11-07T18:03:21.891+0000] {spark_submit.py:490} INFO - py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-11-07T18:03:21.891+0000] {spark_submit.py:490} INFO - py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-07T18:03:21.892+0000] {spark_submit.py:490} INFO - py4j.Gateway.invoke(Gateway.java:238)
[2024-11-07T18:03:21.892+0000] {spark_submit.py:490} INFO - py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-11-07T18:03:21.893+0000] {spark_submit.py:490} INFO - py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-11-07T18:03:21.894+0000] {spark_submit.py:490} INFO - py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-07T18:03:21.894+0000] {spark_submit.py:490} INFO - py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-07T18:03:21.895+0000] {spark_submit.py:490} INFO - java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:03:21.896+0000] {spark_submit.py:490} INFO - 
[2024-11-07T18:03:21.896+0000] {spark_submit.py:490} INFO - The currently active SparkContext was created at:
[2024-11-07T18:03:21.897+0000] {spark_submit.py:490} INFO - 
[2024-11-07T18:03:21.898+0000] {spark_submit.py:490} INFO - (No active SparkContext.)
[2024-11-07T18:03:21.898+0000] {spark_submit.py:490} INFO - 
[2024-11-07T18:03:21.899+0000] {spark_submit.py:490} INFO - at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:120)
[2024-11-07T18:03:21.900+0000] {spark_submit.py:490} INFO - at org.apache.spark.SparkContext.defaultParallelism(SparkContext.scala:2554)
[2024-11-07T18:03:21.900+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-11-07T18:03:21.901+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-11-07T18:03:21.902+0000] {spark_submit.py:490} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-11-07T18:03:21.903+0000] {spark_submit.py:490} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-11-07T18:03:21.903+0000] {spark_submit.py:490} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-11-07T18:03:21.904+0000] {spark_submit.py:490} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-07T18:03:21.904+0000] {spark_submit.py:490} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-11-07T18:03:21.905+0000] {spark_submit.py:490} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-11-07T18:03:21.906+0000] {spark_submit.py:490} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-11-07T18:03:21.906+0000] {spark_submit.py:490} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-07T18:03:21.907+0000] {spark_submit.py:490} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-07T18:03:21.908+0000] {spark_submit.py:490} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-11-07T18:03:21.909+0000] {spark_submit.py:490} INFO - 
[2024-11-07T18:03:22.063+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:22 INFO ShutdownHookManager: Shutdown hook called
[2024-11-07T18:03:22.065+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-146f5703-e71f-4b57-be0a-b81d04836876
[2024-11-07T18:03:22.092+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-146f5703-e71f-4b57-be0a-b81d04836876/pyspark-18d92660-af43-4730-9809-459529355f93
[2024-11-07T18:03:22.118+0000] {spark_submit.py:490} INFO - 24/11/07 18:03:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-e14f69d2-bd25-4dc6-b057-0f3a5637fa00
[2024-11-07T18:03:22.292+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.19.0.2:7077 --name arrow-spark --queue root.default /opt/***/dags/spark_etl_script_docker.py. Error code is: 1.
[2024-11-07T18:03:22.307+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=spark_***_dag, task_id=spark_submit_task, execution_date=20241107T180205, start_date=20241107T180207, end_date=20241107T180322
[2024-11-07T18:03:22.358+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task spark_submit_task (Cannot execute: spark-submit --master spark://172.19.0.2:7077 --name arrow-spark --queue root.default /opt/***/dags/spark_etl_script_docker.py. Error code is: 1.; 1434)
[2024-11-07T18:03:22.428+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-07T18:03:22.479+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
